language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t rsingh26-code/docker-create -f Dockerfile.dev .

script:
 - docker run -e CI=true rsingh26-code/docker-create npm run test -- --coverage

